### ISSUE TITLE
Let's finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-Liliaborrazas#1]
Ahoy @Liliaborrazas !!!

Here you have some tips to improve the exercise:

- [x] Define a good structure of folders and files for the project
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint
- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document (remember to finish the sentence with a semi-colon)
- [x] Fix the logic to generate and save the random number using an English name for the random function
- [x] Define the logic to make the counter work
- [x] Remember to convert input value string to a number
- [x] Extract the feedback painter to a function
- [x] Fix the if's structure: check for the winner option, then the other and the for the rest is enough with an `else` statement
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code
- [x] Write your classes in English!
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

Here you are a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by Liliaborrazas** [comment]
Finished ,Thank you!

**Comment by oneeyedman** [comment]
Well done @Liliaborrazas!!!

Merge your Test branch to Master when you are reday.

Here, have a Well Done gif!
![Well Done](https://media.giphy.com/media/5UyNFT88LPINM1Lzyl/giphy.gif)
